export enum FormControlTypes {
    TextBox = "textbox",
    TextArea = "textarea",
    CheckBox = "checkbox",
    RadioButton = "radiobutton",
    Search = "searchbox",
    DropDown = "DropDown",
    DateInput = "dateinput",
    FileUpload = "fileupload",
    DepDropdown = "depdropdown",
    CustomComponent = "customcomponent",
    Paragraph = "paragraph",
    Info = "infoindicator",
    Link = "link",
    Label = "label",
    TimePicker = "timepicker",
    DateTimePicker = "datetimepicker",
    DatePicker = "datepicker",
    DateRangePicker = "daterangepicker",
    DateTimeRangePicker = 'datetimerangepicker',
    Switch = "switch",
    Table = "table"
}